name: 'Test'

on:
  workflow_dispatch:

jobs:

  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run a docker image
        run: |
          docker run \
          --rm \
          -v ${{ github.workspace }}:/tmp \
          hello-world
